<?php

namespace Kssadi\LogTracker\Console\Commands;

use Illuminate\Console\Command;
use Kssadi\LogTracker\Services\LogExportService;

class CleanupCommand extends Command
{
    protected $signature = 'log-tracker:cleanup
                            {--days=7 : Delete export files older than N days}';

    protected $description = 'Clean up old log export files generated by the log tracker';

    public function __construct(private readonly LogExportService $exportService)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $days = (int) $this->option('days');

        $this->exportService->cleanupOldExports($days);

        $this->info("Cleaned up log export files older than {$days} day(s).");

        return self::SUCCESS;
    }
}
